server:
  port: 9000

spring:
  security:
    user:
      name: william
      password: password
    oauth2:
      client:
        access-token-validity-seconds: 3600
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          apple_health_data_client:
            registration:
              client-id: "apple_health_data_client"
              client-secret: "{noop}secret"
              client-name: Apple Health Data Client
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
                - "resource_owner_password_credentials"
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/apple_health_data_client_oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - read
                - write

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG